# Generated by Django 4.0.4 on 2022-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_message_remove_contact_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.CharField(blank=True, max_length=20, verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='contact',
            name='office',
            field=models.CharField(blank=True, choices=[('bj', '北京'), ('sh', '上海'), ('gz', '广州'), ('cd', '成都')], max_length=20, verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='contact',
            name='salesperson',
            field=models.CharField(blank=True, max_length=10, verbose_name='销售人员'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='下单人邮箱地址'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='po_number',
            field=models.CharField(max_length=10, verbose_name='销售单号（7开头）'),
        ),
    ]
